/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Disclosed } from './disclosed';


export interface HistoryResponse { 
    /**
     * Status of the history entry
     */
    status: HistoryResponse.StatusEnum;
    /**
     * The values that were presented
     */
    disclosed: Array<Disclosed>;
    /**
     * Unique ID of the history entry
     */
    id: string;
    /**
     * The user that owns the key
     */
    user: string;
    /**
     * Values
     */
    value: string;
    /**
     * Relying party
     */
    relyingParty: string;
    relyingPartyLogo: string;
    credentialType: string;
    presentation: string;
    /**
     * Date of creation
     */
    created_at: string;
}
export namespace HistoryResponse {
    export type StatusEnum = 'pending' | 'accepted' | 'declined';
    export const StatusEnum = {
        pending: 'pending' as StatusEnum,
        accepted: 'accepted' as StatusEnum,
        declined: 'declined' as StatusEnum
    };
}


