/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of the key
 */
export type KeyType = 'ES256' | 'ES384' | 'ES512';

export const KeyType = {
    ES256: 'ES256' as KeyType,
    ES384: 'ES384' as KeyType,
    ES512: 'ES512' as KeyType
};

