/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthenticationResponseJSON { 
    authenticatorAttachment?: AuthenticationResponseJSON.AuthenticatorAttachmentEnum;
    id: string;
    rawId: string;
    response: object;
    clientExtensionResults: object;
    type: string;
}
export namespace AuthenticationResponseJSON {
    export type AuthenticatorAttachmentEnum = 'cross-platform' | 'platform';
    export const AuthenticatorAttachmentEnum = {
        cross_platform: 'cross-platform' as AuthenticatorAttachmentEnum,
        platform: 'platform' as AuthenticatorAttachmentEnum
    };
}


