/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CredentialIssuer } from './credentialIssuer';


export interface CredentialResponse { 
    issuer: CredentialIssuer;
    credential: object;
    id: string;
    user: string;
    value: string;
    metaData: object;
    exp?: string;
    status?: string;
}

