/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TxCodeInfo { 
    input_mode?: TxCodeInfo.InputModeEnum;
    description?: string;
    length?: number;
}
export namespace TxCodeInfo {
    export type InputModeEnum = 'numeric' | 'text';
    export const InputModeEnum = {
        numeric: 'numeric' as InputModeEnum,
        text: 'text' as InputModeEnum
    };
}


