export * from './auth.service';
import { AuthApiService } from './auth.service';
export * from './credentials.service';
import { CredentialsApiService } from './credentials.service';
export * from './default.service';
import { DefaultApiService } from './default.service';
export * from './history.service';
import { HistoryApiService } from './history.service';
export * from './oid4vci.service';
import { Oid4vciApiService } from './oid4vci.service';
export * from './oid4vp.service';
import { Oid4vpApiService } from './oid4vp.service';
export * from './settings.service';
import { SettingsApiService } from './settings.service';
export const APIS = [AuthApiService, CredentialsApiService, DefaultApiService, HistoryApiService, Oid4vciApiService, Oid4vpApiService, SettingsApiService];
