/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StatusList { 
    bitsPerStatus: StatusList.BitsPerStatusEnum;
    id: string;
    list: object;
    positions: string;
    jwt: string;
    exp: number;
}
export namespace StatusList {
    export type BitsPerStatusEnum = 1 | 2 | 4 | 8;
    export const BitsPerStatusEnum = {
        NUMBER_1: 1 as BitsPerStatusEnum,
        NUMBER_2: 2 as BitsPerStatusEnum,
        NUMBER_4: 4 as BitsPerStatusEnum,
        NUMBER_8: 8 as BitsPerStatusEnum
    };
}


